### ISSUE TITLE
UWP In VS2022 Release Mode dont work  

### ISSUE THREAD

**Issue by TheGrumpyT** [rbfx/rbfx-csharp-thirdperson#1] opened 2024-01-25 22:00 UTC
When i start the UWP project in releasemode it throws a "Platform is not supported" 

in Debug mode it starts with no Problem.

**Comment by gleblebedev** [comment] 2024-01-25 22:02
May I ask you to try manually set target CPU architecture to x64?

**Comment by gleblebedev** [comment] 2024-01-25 22:28
@TheGrumpyT I was able to reproduce the issue.

**Comment by TheGrumpyT** [comment] 2024-01-25 22:44
Yes, i set it to x64. ( was that a mistake? )

I use always x64 for UWP. (for Testing on my XBOX ONE)

On Any CPU it throws this error 

The BaseOutputPath/OutputPath property is not set for project 'RbfxTemplate.UWP.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.

**Comment by gleblebedev** [comment] 2024-01-26 10:05
@TheGrumpyT by the way how did you discover the template?

**Comment by TheGrumpyT** [comment] 2024-01-26 10:40
I have searched with google for an Urho3d template that I can also use with C# and then landed here.
I am looking for a small and fast 3d engine that I can also use on my XBOX.

And this template looks very interesting.

**Comment by gleblebedev** [comment] 2024-01-26 23:57
Thank you!

I've fixed the issue you mentioned, you'll need to update Urho3DNet package when it's ready. But there is one more problem down the line with custom component creation. I'll update the issue when I fix it too.

**Comment by TheGrumpyT** [comment] 2024-01-28 13:34
Thank you!

**Comment by gleblebedev** [comment] 2024-01-29 22:56
@TheGrumpyT  It seems I made it work except some .NET Native tool breaks rbfx'es .net glue code. Do you know if it's possible to publish a game to store that isn't compiled with native tool chain?

**Comment by TheGrumpyT** [comment] 2024-01-31 17:02
I think a release in the store requires a native compilation.

**Comment by gleblebedev** [comment] 2024-01-31 17:13
@TheGrumpyT ugh... Then I have to fix the issue.

The problem is that 
extern Urho3D_CSharpCreateObjectCallback Urho3D_CSharpCreateObject;
callback gets screwed if NativeAOT compilation is enabled. I'll try a different way of passing the callback to native code, hopefully it will work.

Also this issue corelates to a bigger problem we have with AOT compilation for Web. If we tackle that one we'll have web as one of the targets for .net. Just thinking out loud.

**Comment by gleblebedev** [comment] 2024-02-19 21:02
@TheGrumpyT I'm sorry it took me so long. The problem is fixed now. I re-enabled native tools for the UWP Release.

**Closed as completed by gleblebedev** 2024-02-19 21:02 UTC
